site_name: seLab
nav:
  - Main: seLab.md
  - Professer: Propfesser.md
  - Members: Members.md
  - Research&Projects: Research&Projects.md
  - Resources: Resources.md
  - Photo: Photo.md
  - Contact: Contact.md